name: Sync to Hugging Face Spaces
on:
  push:
    branches: [main] # Agar aapki branch ka naam 'master' hai toh yahan change kar lena
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force https://pushphans:$HF_TOKEN@huggingface.co/spaces/Pushphans/basic-chatbot main